language: node_js
os:
- windows
- linux
- osx
node_js:
  - '14'
  - '12'
  - '10'
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./bin/index.js          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x ./bin/index.js          ; fi
